server:
  port: 7500
spring:
  application:
    name: micro-service-consumer-movie-ribbon-with-hystrix
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:abc.123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
#hystrix.command.default.execution.thread.timeoutInMilliseconds: 5000