server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: micro-service-provider-user
logging:
  level: info
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
     defaultZone: http://root1:abc.1@peer1:8761/eureka/
  instance:
    prefer-ip-address: true
