server:
  port: 7902
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
       defaultZone: http://root:abc.123@localhost:8761/eureka    #localhost前面一定要加http://不加会抛异常
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: micro-service-consumer-movie-ribbon-properties-customizing

micro-service-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule