spring:
  application:
    name: micro-service-gateway-zuul
server:
  port: 7200
eureka:
  client:
    service-url:
      defaultZone: http://root:abc.123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    micro-service-provider-user: /api/**
  ignored-services: '*'

