server:
  port: 7900
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level: info
