DROP TABLE user IF EXISTS;
CREATE TABLE user (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(20),
  name     VARCHAR(20),
  age      INT(3),
  balance  DECIMAL,
  PRIMARY KEY (id)
);